// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ObliteracyDotNet.Generators.Templates.ConfigFiles
{
    using System;
    
    
    #line 1 "C:\Users\Josh\Dropbox\Code\Generators\DomTester\ServiceDom\Templates\ConfigFiles\EdmxFile.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class EdmxFile : EdmxFileBase
    {
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\"?>\r\n  <edmx:Edmx Version=\"2.0\" xmlns:edmx=\"http://schemas.micr" +
                    "osoft.com/ado/2008/10/edmx\">\r\n    <!-- EF Runtime content -->\r\n    <edmx:Runtime" +
                    ">\r\n      <!-- SSDL content -->\r\n      <edmx:StorageModels>\r\n        ");
            
            #line 11 "C:\Users\Josh\Dropbox\Code\Generators\DomTester\ServiceDom\Templates\ConfigFiles\EdmxFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SSDL));
            
            #line default
            #line hidden
            this.Write("\r\n      </edmx:StorageModels>\r\n      <!-- CSDL content -->\r\n      <edmx:Conceptua" +
                    "lModels>\r\n        ");
            
            #line 15 "C:\Users\Josh\Dropbox\Code\Generators\DomTester\ServiceDom\Templates\ConfigFiles\EdmxFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSDL));
            
            #line default
            #line hidden
            this.Write("\r\n      </edmx:ConceptualModels>\r\n      <!-- C-S mapping content -->\r\n      <edmx" +
                    ":Mappings>\r\n        ");
            
            #line 19 "C:\Users\Josh\Dropbox\Code\Generators\DomTester\ServiceDom\Templates\ConfigFiles\EdmxFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MSL));
            
            #line default
            #line hidden
            this.Write(@"
      </edmx:Mappings>
    </edmx:Runtime>
    <!-- EF Designer content (DO NOT EDIT MANUALLY BELOW HERE) -->
    <edmx:Designer xmlns=""http://schemas.microsoft.com/ado/2008/10/edmx"">
      <edmx:Connection>
        <DesignerInfoPropertySet>
          <DesignerProperty Name=""MetadataArtifactProcessing"" Value=""EmbedInOutputAssembly"" />
        </DesignerInfoPropertySet>
      </edmx:Connection>
      <edmx:Options>
        <DesignerInfoPropertySet>
          <DesignerProperty Name=""ValidateOnBuild"" Value=""true"" />
          <DesignerProperty Name=""EnablePluralization"" Value=""True"" />
        </DesignerInfoPropertySet>
      </edmx:Options>
      <!-- Diagram content (shape and connector positions) -->
      <edmx:Diagrams>
        <Diagram Name=""Model1"" />
      </edmx:Diagrams>
    </edmx:Designer>
  </edmx:Edmx>
");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Josh\Dropbox\Code\Generators\DomTester\ServiceDom\Templates\ConfigFiles\EdmxFile.tt"

private string _SSDLField;

/// <summary>
/// Access the SSDL parameter of the template.
/// </summary>
private string SSDL
{
    get
    {
        return this._SSDLField;
    }
}

private string _CSDLField;

/// <summary>
/// Access the CSDL parameter of the template.
/// </summary>
private string CSDL
{
    get
    {
        return this._CSDLField;
    }
}

private string _MSLField;

/// <summary>
/// Access the MSL parameter of the template.
/// </summary>
private string MSL
{
    get
    {
        return this._MSLField;
    }
}


public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool SSDLValueAcquired = false;
if (this.Session.ContainsKey("SSDL"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["SSDL"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'SSDL\' did not match the type of the da" +
                "ta passed to the template.");
    }
    else
    {
        this._SSDLField = ((string)(this.Session["SSDL"]));
        SSDLValueAcquired = true;
    }
}
if ((SSDLValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("SSDL");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'SSDL\' did not match the type of the da" +
                    "ta passed to the template.");
        }
        else
        {
            this._SSDLField = ((string)(data));
        }
    }
}
bool CSDLValueAcquired = false;
if (this.Session.ContainsKey("CSDL"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["CSDL"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'CSDL\' did not match the type of the da" +
                "ta passed to the template.");
    }
    else
    {
        this._CSDLField = ((string)(this.Session["CSDL"]));
        CSDLValueAcquired = true;
    }
}
if ((CSDLValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("CSDL");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'CSDL\' did not match the type of the da" +
                    "ta passed to the template.");
        }
        else
        {
            this._CSDLField = ((string)(data));
        }
    }
}
bool MSLValueAcquired = false;
if (this.Session.ContainsKey("MSL"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["MSL"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'MSL\' did not match the type of the dat" +
                "a passed to the template.");
    }
    else
    {
        this._MSLField = ((string)(this.Session["MSL"]));
        MSLValueAcquired = true;
    }
}
if ((MSLValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("MSL");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'MSL\' did not match the type of the dat" +
                    "a passed to the template.");
        }
        else
        {
            this._MSLField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class EdmxFileBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
